name: school_management_app
description: A school management application with modern Flutter architecture.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  get_it: ^7.6.4
  auto_route: ^7.8.3
  json_annotation: ^4.8.1
  fl_chart: ^0.61.0
  pdf: ^3.10.2
  excel: ^2.0.0
  image_picker: ^1.0.4
  file_picker: ^5.3.3
  url_launcher: ^6.2.2
  table_calendar: ^3.0.9
  qr_flutter: ^4.2.0
  mobile_scanner: ^3.1.0+1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  animations: ^2.0.7
  flutter_staggered_animations: ^1.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
